name: Build WebView APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install Bubblewrap
        run: npm install -g @bubblewrap/cli

      - name: Init TWA project
        run: |
          bubblewrap init --manifest=https://data-keuangan-aziva.web.app/manifest.json --directory=twa-project --force
          cd twa-project
          bubblewrap build

      - name: Upload APK to GitHub Releases
        uses: ncipollo/release-action@v1
        with:
          tag: latest
          name: WebView APK
          files: twa-project/*.apk
