name: Build TWA APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      # Setup Java 17
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "17"

      # Setup Android SDK
      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
        with:
          sdk-version: 34.0.0

      # Install Bubblewrap
      - name: Install Bubblewrap
        run: npm install -g @bubblewrap/cli

      # Init TWA project (Non-interaktif sepenuhnya)
      - name: Init TWA project
        run: |
          npx bubblewrap init \
            --manifest=https://data-keuangan-aziva.web.app/manifest.json \
            --directory=twa-project \
            --force \
            --usePlaySigning=false \
            --skipPrompt \
            --packageId=com.aziva.keuangan \
            --jdkPath=$JAVA_HOME

      # Build APK
      - name: Build APK
        working-directory: twa-project
        run: bubblewrap build

      # Upload APK
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: twa-apk
          path: twa-project/app-release-signed.apk