name: Build TWA APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Bubblewrap
        run: npm install -g @bubblewrap/cli

      - name: Prepare TWA manifest
        run: |
          mkdir twa-project
          cat > twa-project/twa-manifest.json <<EOF
{
  "name": "Aziva",
  "short_name": "Aziva",
  "start_url": "https://data-keuangan-aziva.web.app/",
  "theme_color": "#ffffff",
  "background_color": "#ffffff",
  "display": "standalone",
  "orientation": "portrait",
  "scope": "https://data-keuangan-aziva.web.app/",
  "host": "data-keuangan-aziva.web.app",
  "launcherName": "Aziva",
  "generatorApp": "bubblewrap-cli",
  "fallbackType": "customtabs",
  "signingKey": {
    "path": "my-release-key.jks",
    "alias": "my-key-alias"
  }
}
EOF

      - name: Init TWA project
        run: |
          cd twa-project
          bubblewrap init --manifest twa-manifest.json --force --usePlaySigning=false

      - name: Build APK
        run: |
          cd twa-project
          bubblewrap build

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: aziva-release-apk
          path: twa-project/app-release.apk