name: Build TWA APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "17"

      - name: Install Bubblewrap
        run: npm install -g @bubblewrap/cli

      - name: Init TWA project
        run: |
          yes | npx bubblewrap init \
            --manifest=https://data-keuangan-aziva.web.app/manifest.json \
            --directory=twa-project \
            --force \
            --usePlaySigning=false \
            --skipPrompt
            --packageId=com.azivastore.app
            

      - name: Build APK
        working-directory: twa-project
        run: bubblewrap build

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: twa-apk
          path: twa-project/app-release-signed.apk
