name: Build TWA APK

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Setup Java (untuk Bubblewrap)
      - name: Setup Java 17
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "17"
          # Hapus cache gradle karena tidak digunakan
          cache: "none"

      # Setup Node.js (untuk Bubblewrap)
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"

      # Install Bubblewrap
      - name: Install Bubblewrap
        run: npm install -g @bubblewrap/cli

      # Inisialisasi project TWA
      - name: Initialize TWA Project
        run: |
          # Skip instalasi JDK dan Android SDK karena sudah disetup oleh GitHub Actions
          export BUBBLEWRAP_DISABLE_SDK_INSTALLATION=true
          yes | bubblewrap init \
            --manifest=https://data-keuangan-aziva.web.app/manifest.json \
            --directory=twa-project \
            --force \
            --usePlaySigning=false \
            --skipPrompt \
            --packageId=com.aziva.keuangan

      # Build APK
      - name: Build APK
        working-directory: twa-project
        run: |
          # Set environment variables untuk build Android
          export ANDROID_HOME=$ANDROID_SDK_ROOT
          export PATH=$PATH:$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools
          
          bubblewrap build \
            --skipVersionCheck \
            --skipPwaValidation

      # Upload hasil APK
      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: twa-apk
          path: twa-project/app-release-signed.apk
          retention-days: 7