name: Build TWA APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      # Menginstal Java Development Kit (JDK)
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "17"

      # Menginstal Android SDK (termasuk build-tools)
      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
        with:
          sdk-version: 34.0.0
          
      - name: Install Bubblewrap
        run: npm install -g @bubblewrap/cli

      - name: Install Bubblewrap & Initialize TWA
        run: |
          yes | npx bubblewrap init \
            --manifest=https://data-keuangan-aziva.web.app/manifest.json \
            --directory=twa-project \
            --force \
            --usePlaySigning=false \
            --skipPrompt \
            --packageId=com.aziva.keuangan

      - name: Build APK
        working-directory: twa-project
        run: bubblewrap build

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: twa-apk
          path: twa-project/app-release-signed.apk
          
          
          
          